language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
install:
  - pip install flake8 pep257 --use-mirrors
  - python setup.py install
before_script:
  - flake8 praw
  - flake8 tests
  - pep257 praw
script:
  - REDDIT_SITE=reddit_bypass_cdn python setup.py test -s tests.BasicTest
  - REDDIT_SITE=reddit_bypass_cdn python setup.py test -s tests.OAuth2Test
  - REDDIT_SITE=reddit_bypass_cdn python setup.py test -s tests.ModeratorSubredditTest.test_mod_mail_send
