language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - nightly
  - pypy
  - pypy3
matrix:
  allow_failures:
    - python: nightly
sudo: false
install: pip install coveralls flake8 pep257 betamax_matchers
script:
  - flake8 praw
  - flake8 tests
  - pep257 praw
  - coverage run --source=praw setup.py test
after_success: coveralls
